version: "2"

services: 
  api-products:
    image: bitnami/postgresql
    ports: 
      - 5432:5432 
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=productsmanegment