import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  UserButton,
  SignedOut,
  SignInButton,
  SignUpButton,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-end mb-5 p-3 w-[100%]">
            <SignedIn>
              <UserButton />
            </SignedIn>
            <div className="flex gap-5">
              <SignedOut>
                <SignInButton>
                  <Button>Entrar</Button>
                </SignInButton>
                <SignUpButton>
                  <Button>Criar conta</Button>
                </SignUpButton>
              </SignedOut>
            </div>
          </header>

          <div className="m-auto max-w-screen-xl">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
